name: Update stars list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My Awesome list
        uses: simonecorsi/mawesome@v2.2.0
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-email: ${{ secrets.USER_EMAIL }}
          github-name: ${{ github.repository_owner }}
          template-path: "/template/README.ejs"
